

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{
        background: 'black',
        color: "white",
        width: '100%',
        height: '100vh'
      }}>
        {children}
      </body>
      </html>
  )
}
